# https://embarkstudios.github.io/cargo-deny/

[graph]
targets = [
    { triple = "aarch64-apple-darwin" },
    { triple = "aarch64-linux-android" },
    { triple = "x86_64-apple-darwin" },
    { triple = "x86_64-pc-windows-msvc" },
    { triple = "x86_64-unknown-linux-gnu" },
    { triple = "x86_64-unknown-linux-musl" },
]


[licenses]
confidence-threshold = 0.93
allow = [
    "Apache-2.0 WITH LLVM-exception",
    "Apache-2.0",
    "BSD-2-Clause",
    "BSD-3-Clause",
    "MIT",
    "MIT-0",
    "MPL-2.0",
    "Unicode-DFS-2016",
]

[[licenses.exceptions]]
allow = ["WTFPL"]
name = "pcx"
version = "*"

[advisories]
yanked = "deny"
ignore = []


[bans]
multiple-versions = "deny"
wildcards = "allow" # at least until https://github.com/EmbarkStudios/cargo-deny/issues/241 is fixed
deny = []
skip = [
    { name = "bitflags" },   # Some deps depend on 1.3.2 while others on 2.6.0
    { name = "hashbrown" },  # Some deps depend on 0.13.2 while others on 0.14.5
    { name = "miniz_oxide" } # Some deps depend on 0.7.4 while others on 0.8.0
]
